server:
  port: 6000
spring:
  application:
    name: blueberry-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blueberry?charsetEncoding=utf8mb4&serverTimezone=Asia/Shanghai
    username: xiguapi
    password: xiguapi777@!#

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 输出SQL